[package]
name = "typemap_rev"
version = "0.1.0"
authors = ["kingbri <bdashore3@gmail.com>", "alex <acdenissk69@gmail.com>"]
license = "MIT"
repository = "https://github.com/bdashore3/typemap_rev"
homepage = "https://github.com/bdashore3/typemap_rev"
edition = "2018"

[dependencies]
